# Generated by Django 3.2.4 on 2021-06-19 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(auto_now=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('team_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team_images/%Y/%m')),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(auto_now=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('biography', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=63)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userteam', to='timeline.userteam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='TimeLineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(auto_now=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=200)),
                ('message_image', models.ImageField(blank=True, null=True, upload_to='message_images/%Y/%m')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='timeline.userprofile')),
            ],
            options={
                'verbose_name': 'Durum Mesajı',
                'verbose_name_plural': 'Durum Mesajları',
            },
        ),
    ]
